@startuml
left to right direction
skinparam actorStyle Hollow

actor Employee
actor Time
actor Company <<Client>>
actor EmployeeAdmin
actor ExternalReviewer
actor FinancialManager
actor ProjectManager
actor User

User <|--- Employee #green;text:green : extends 
User <|--- ExternalReviewer #green;text:green : extends 
EmployeeAdmin ---|> Employee  #green;text:green : extends 
ProjectManager ---|> Employee  #green;text:green : extends 
ExternalReviewer <|--- Company  #green;text:green : extends 
EmployeeAdmin ---|> FinancialManager #green;text:green : extends 
FinancialManager ---|> Company #green;text:green : extends 

/' Employee use cases'/
usecase syncEmployee
usecase listEmployees
usecase showEmployee
usecase sendNotificationToEmployee

usecase createCompany
usecase listCompanies
usecase showCompany
usecase updateCompany
usecase deleteCompany

usecase createProject
usecase updateProject
usecase deleteProject
usecase listProjects
usecase showProject

usecase listPurchases
usecase showPurchase

usecase listInvoices
usecase showInvoice
usecase exportInvoice
usecase exportInvoices
usecase createInvoice
usecase recalculateInvoice
usecase declareToTaxAuthorities
usecase changeStatusOfInvoice
usecase deleteInvoice

usecase login
usecase logout
usecase updatePassword
usecase resetPassword

usecase createEntry
usecase updateEntry
usecase deleteEntry

usecase createDepartment
usecase listDepartments
usecase showDepartment
usecase updateDepartment
usecase deleteDepartment

Time ---> syncEmployee 
Time ---> sendNotificationToEmployee

Employee ---> createEntry
Employee ---> updateEntry
Employee ---> deleteEntry

Employee ---> listEmployees
Employee ---> showEmployee

Employee ---> listProjects
Employee ---> showProject

EmployeeAdmin ---> createCompany
EmployeeAdmin ---> listCompanies
EmployeeAdmin ---> showCompany
EmployeeAdmin ---> updateCompany
EmployeeAdmin ---> deleteCompany

EmployeeAdmin ---> createProject
EmployeeAdmin ---> updateProject
EmployeeAdmin ---> deleteProject

EmployeeAdmin ---> createDepartment
EmployeeAdmin ---> listDepartments
EmployeeAdmin ---> showDepartment
EmployeeAdmin ---> updateDepartment
EmployeeAdmin ---> deleteDepartment


ExternalReviewer ---> listProjects
ExternalReviewer ---> showProject

Company ---> listPurchases
Company ---> showPurchase

Company ---> listInvoices
Company ---> showInvoice
Company ---> exportInvoice
Company ---> exportInvoices

FinancialManager ---> createInvoice
FinancialManager ---> recalculateInvoice
FinancialManager ---> changeStatusOfInvoice
FinancialManager ---> declareToTaxAuthorities
FinancialManager ---> deleteInvoice

User ---> login
User ---> logout
User ---> updatePassword
User ---> resetPassword

@enduml