@startuml
  class Holding
  class Employee
  class Reviewer
  class Client
  class Company
  class Notification
  class DaysOff
  class Project {
    + id
    + parentId
    + name
    + hourPrice
    + deadLine
    + paymentDeadLine
  }
  class Department {
    + type: DepartmentType
  }
  class DepartmentType << enumeration >> {
    design
    markup
    development
  }
  class Entry {
    + description
    + concept
    + timestamp
  }
  class EmployeeEntry implements Entry
  class BagEntry implements Entry {
    + id
    + startDate
    + totalHours
    + remainingHours()
  }
  class AssumedEntry implements Entry
  class HostingEntry implements Entry
  class Invoice {
    + date
    + base
    + tax
    + isDeclared
    + status: InvoiceStatus
  }
  class InvoiceStatus << enumeration >> {
    issued
    paid
    partial
    created
    pending
  }
  class CorrectiveInvoice
  
  Holding *-- Company
  Company *-- Project
  Company ..> Client
  Company ..> Reviewer
  Project ..> Department
  Project ..> Employee
  Project *-- Entry
  Project *-- Invoice
  Project -- Project
  Entry *-- Employee
  Entry *-- Department
  Employee --> Notification
  Employee --> DaysOff
  Invoice ..> CorrectiveInvoice
  Invoice +-- InvoiceStatus
  Department +-- DepartmentType

@enduml