@startuml
  class Holding
  class Worker
  class Reviewer
  class Client
  class Company
  class Notification
  class Project {
    + hourPrice
    + deadLine
    + paymentDeadLine
  }
  class Department {
    + type: DepartmentType
  }
  class DepartmentType << enumeration >> {
    design
    markup
    development
  }

  class Entry {
    + description
    + concept
    + timestamp
  }
  class WorkerEntry implements Entry
  class BagEntry implements Entry
  class AssumedEntry implements Entry
  class HostingEntry implements Entry
  class Invoice {
    + isDeclared
    + type: InvoiceType
  }
  class InvoiceType << enumeration >> {
    issued
    paid
    partial
    created
    pending
  }
  class CorrectiveInvoice
  
  
  Holding *-- Company
  Company *-- Project
  Company ..> Client
  Company ..> Reviewer
  Project ..> Department
  Project ..> Worker
  Project *-- Entry
  Entry *-- Worker
  Entry *-- Department
  Project *-- Invoice
  Worker --> Notification
  Invoice ..> CorrectiveInvoice
  Invoice +-- InvoiceType
  Department +-- DepartmentType

@enduml